server:
    port: 8085
#    contextPath: /swagger2-demo/v2/api-docs

spring:
 
    application:
        name: trading
    devtools:
        restart:
            enabled: true
    h2:
        console:
            enable: true
            settings:
                web-allow-others: true
                path: /h2

    
    datasource:
      url: jdbc:h2:file:~/tradeDB;DB_CLOSE_DELAY=-1
      username: sa
      password: ""
      driverClassName: org.h2.Driver
        
        
    jpa:
#        hibernate.ddl-auto: create
#        generate-ddl: true
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        

jwt_secret: 5B4CF7D3FC4579796F1D9898EDFE1

hibernate:
      naming-strategy:org.hibernate.cfg.DefaultComponentSafeNamingStrategy